version: '3.9'

services:
  database:
    image: postgres
    container_name: cnpjquery
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_USER}
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local